# Generated by Django 5.0.3 on 2024-03-18 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_admin_student_mst_student_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_mst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.CharField(max_length=100)),
                ('admin_firstname', models.CharField(max_length=100)),
                ('admin_lastname', models.CharField(max_length=100)),
                ('admin_email', models.EmailField(max_length=254, unique=True)),
                ('admin_mobile', models.CharField(max_length=15)),
                ('admin_password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_mst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_username', models.CharField(max_length=100)),
                ('user_firstname', models.CharField(max_length=100)),
                ('user_lastname', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_mobile', models.CharField(max_length=15)),
                ('user_password', models.CharField(blank=True, max_length=100, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='components.admin_mst')),
            ],
        ),
        migrations.DeleteModel(
            name='Admin_Student_mst',
        ),
        migrations.DeleteModel(
            name='Admin_Teacher_mst',
        ),
    ]
