# Generated by Django 5.0.3 on 2024-03-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_admin_mst_superadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_mst',
            name='admin_username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user_mst',
            name='user_username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
